### ISSUE TITLE
화이트라벨 에러 페이지

### ISSUE THREAD

**Issue by kyungmin0228** [KimKiHyun0206/SELab-ToyProject-2024#16]
This application has no explicit mapping for /error, so you are seeing this as a fallback.

There was an unexpected error (type=Not Found, status=404).

라고 뜹니다

**Comment by kyungmin0228** [comment]
![image](https://github.com/user-attachments/assets/4c6e8d6e-8fb1-4fc1-a2be-79f8a3ac6811)

**Comment by Duskafka** [comment]
컨트롤러에서 매핑을 잘못하면 그렇게 나옵니다
