### ISSUE TITLE
[ ToDoList ] 소민섭

### ISSUE THREAD

**Issue by Duskafka** [KimKiHyun0206/SELab-ToyProject-2024#3]
# 연평도 몽쉘도둑 소민섭이 할 일

**Comment by Duskafka** [comment]
# 깃허브 사용법 공부하기
1. push, commit, merge
2. banch, master
3. commit message templte

**Comment by sominseob** [comment]
자고싶어요

**Comment by Duskafka** [comment]
잠은 죽어서 자도록

**Comment by sominseob** [comment]
오,,...

**Comment by Duskafka** [comment]
# 자바의 기본적인 문법
- 클래스
- 메소드 선언
- 변수 선언
- 인터페이스 구현

# 객체지향 설계란 무엇인가?
- SOLID 원칙
- 객체란 무엇인가
- 캡슐화, 다형성, 상속

**Comment by Duskafka** [comment]
# 스프링이란 무엇인가?
* 프레임워크란 무엇인가

# HTTP Method란 무엇인가
* 상태코드
* Patch, Put, Delete, Get ...
* MVC 모델이란 무엇인가


# 기타 공부할 것
* 왜 웹이서 객체지향 언어를 사용하는가
* TDD, DDD ,RDD 란 무엇인가

**Comment by Duskafka** [comment]
* SQL
* JDBC
