### ISSUE TITLE
develop_js / myPage Bug

### ISSUE THREAD

**Issue by sominseob** [KimKiHyun0206/SELab-ToyProject-2024#44]
# 버그 내용
로그인 후 마이페이지에 들어가면 401에러가 뜨는 오류 하지만
로그인 후 로그아웃을 시킨 뒤 다시 로그인을 하면 마이페이지 접근 가능

**Comment by Duskafka** [comment]
일단 처음에 요청할 때 헤더에 토큰이 안 담기네요. 두번째로 할 때부터 헤더에 담깁니다

**Comment by Duskafka** [comment]
로깅을 해서 어디에서 문제가 발생하는지 확인해보세요
